FROM node:23-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn \
    yarn install

COPY . .

RUN yarn run build



FROM node:23-alpine AS production

COPY --from=builder /app/package.json ./

COPY --from=builder /app/dist ./dist

RUN yarn global add serve

EXPOSE 4000

CMD ["yarn", "run", "start:prod"]
