version: '3.8'
services:
  mova-api:
    build: ./api
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - APP_PORT=9000
      - NODE_ENV=development
    volumes:
      - ./api:/app
    depends_on:
      - mova-db
      - mova-index

  mova-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9002:3306
    environment:
      MYSQL_USER: mova
      MYSQL_PASSWORD: secret-to-mova-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mova
    restart: always
    volumes:
      - mova-db:/var/lib/mysql

  mova-index:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - 9003:9200
      - 9004:9300
    volumes:
      - mova-index:/usr/share/elasticsearch/data

  mova-client:
    build: ./client
    ports:
      - 9005:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    volumes:
      - ./client:/app
    depends_on:
      - mova-api
volumes:
  mova-db:
  mova-index: