version: '3.8'
services:
  mova-api:
    image: mova-api:prod
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 9000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - mova-db
      - mova-index
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          cpus: '4.0'
          memory: 256M

  mova-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9002:3306
    environment:
      MYSQL_USER: mova
      MYSQL_PASSWORD: secret-to-mova-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mova
    volumes:
      - mova-db:/var/lib/mysql
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          cpus: '4.0'
          memory: 256M

  mova-index:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9003:9200
      - 9004:9300
    volumes:
      - mova-index:/usr/share/elasticsearch/data
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          cpus: '4.0'
          memory: 512M

  mova-client:
    image: mova-client:prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 9005:4000
    environment:
      - NODE_ENV=production
    depends_on:
      - mova-api
    deploy:
      resources:
        reservations:
          memory: 64M
        limits:
          cpus: '0.5'
          memory: 128M

  mova-nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mova-api
      - mova-client

volumes:
  mova-db:
  mova-index:
