version: '3.8'
services:
  mova-api:
    image: mova-api:dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 9000:3000
      - 9001:3001
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
    depends_on:
      - mova-db
      - mova-index

  mova-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9002:3306
    environment:
      MYSQL_USER: mova
      MYSQL_PASSWORD: secret-to-mova-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mova
    restart: always
    volumes:
      - mova-db-dev:/var/lib/mysql

  mova-index:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - 9003:9200
      - 9004:9300
    volumes:
      - mova-index-dev:/usr/share/elasticsearch/data
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          cpus: '4.0'
          memory: 4G

  mova-client:
    image: mova-client:dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 9005:4000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
    depends_on:
      - mova-api

  mova-nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./nginx:/etc/nginx
    depends_on:
      - mova-api
      - mova-client

volumes:
  mova-db-dev:
  mova-index-dev:
