version: '3.8'
services:
  mova-api:
    build: ./api
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - APP_PORT=9000
      - NODE_ENV=development
    volumes:
      - ./api:/app
    depends_on:
      - mova-db

  mova-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - mova-db:/var/lib/postgresql/data

  mova-client:
    build: ./client
    ports:
      - 9005:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    volumes:
      - ./client:/app
    depends_on:
      - mova-api
volumes:
  mova-db: